### ISSUE TITLE
Pytest error: unrecognized arguments in pytest.ini

### ISSUE THREAD

**Issue by andreas-bauer** [JulianFrattini/cira#10]
When running Pytest it throws the following error:

```sh
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov-report --cov=src
  inifile: /Users/.../cira/pytest.ini
  rootdir: /Users/.../cira
```

The arguments are not supported anymore.

@JulianFrattini What output regarding the code coverage report is desired?

Pytest version 7.1.0

**Comment by JulianFrattini** [comment]
The error was likely caused due to the [pytest-cov](https://pypi.org/project/pytest-cov/) package missing. It has been added to the requirements.txt now and should solve the error.

**Comment by andreas-bauer** [comment]
Yes, it solved the problem.
