### ISSUE TITLE
Fix environment variables in container

### ISSUE THREAD

**Issue by JulianFrattini** [JulianFrattini/cira#15]
Currently, if a `.env` file exists to define the location of the models and the code is run locally once after the docker container had been started, the environment variables within the container are seemingly overwritten. Within the container, the variables are non-recoverable. To ensure that the code can be used in parallel on a local machine as well as in the container, the environment variables need to be handled properly. 

Potential solutions:

* Start the container with a specific `.env` file that overwrites the local environment variables.
* Only store the model location in the environment variables for the docker container (and hardcode it in the local environment).

**Comment by andreas-bauer** [comment]
One other solution could be to set a env like `"containerEnv": { "DEV_CONTAINER": TRUE  }` in `devcontainer.json` so that you can determine in Python if you are running your code inside a container or not.

```python
# only load .env file environment if not in devcontainer
if os.environ.get('DEV_CONTAINER') == None:
   dotenv.load_dotenv()

print(os.environ['MODEL_CLASSIFICATION']
print(os.environ['MODEL_LABELING']
```
