### ISSUE TITLE
Update HTTP Methods to comply to Fetch Standard

### ISSUE THREAD

**Issue by JulianFrattini** [JulianFrattini/cira#40]
According to the [fetch standard](https://fetch.spec.whatwg.org), [a http-compliant GET request should not contain a body](https://github.com/whatwg/fetch/issues/551). However, the API in `app.py` contains GET endpoints that require a body. 

While some clients (e.g., Postman) allow deviation from the fetch standard, other clients (e.g., the fetch library in JavaScript) will cause something like the following error message: `TypeError: Window.fetch: HEAD or GET Request cannot have a body.` This makes the CiRA functionality unusable as one container within a composition, e.g., as the backend to a web interface.

Consequently, it is suggested to update the HTTP method of all API endpoints that require a body from GET to POST.

**Comment by andreas-bauer** [comment]
Please have a look at [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) to determine which HTTP method could be used.

- **GET**: Is Idempotent and Cacheable
- **PUT**: Is Idempotent but **not** Cacheable
- **POST**: Is **not** Idempotent  and Cacheable only if freshness information is included

**Comment by JulianFrattini** [comment]
According to the classification, the request should be a **GET**, which is not allowed by the fetch specifications. What method would you recommend?

**Comment by JulianFrattini** [comment]
Or is it actually a **GET** method and our approach of requiring a body for the function is wrong?

**Comment by andreas-bauer** [comment]
My recommendation:

- Use **GET** with query parameters if the input sentence is simple and does not include any special characters. It is simple and caching would be possible.
- Use **PUT** if you want to use the body for input and the functions do not have any side effects and therefore are idempotent.
- Use **POST** if there are side effects.
