### ISSUE TITLE
Correctly parse brackets

### ISSUE THREAD

**Issue by JulianFrattini** [JulianFrattini/cira#57]
The usage of sentences containing brackets causes the code to break. For example, the sentence "Before access permissions are deactivated, I receive information as to which app functions will no longer work (in full)." from the [corona warn app](https://github.com/corona-warn-app/cwa-documentation/blob/main/scoping_document.md) causes an internal server error at the following position:

```
  ...
  File ".\cira\src\converters\sentencetolabels\labelingconverter.py", line 197, in position_of_next_token
    position_of_token = re.search(token, sentence[cursor_pos:]).start()
  ...
```

**Comment by andreas-bauer** [comment]
Would a simple filter for special characters be sufficient, or does the content within the brackets needs to be transformed into something else?

**Comment by JulianFrattini** [comment]
Content within brackets does not need to be transformed into something else. Indeed, the [original study creating the labeled data set](https://arxiv.org/abs/2202.00932) disregarded all content within brackets completely. Hence, you are right. My guess is that it just screws up the cursor positioning when processing the sentence. I will open a branch to patch this.
