### ISSUE TITLE
Revise model locator test

### ISSUE THREAD

**Issue by JulianFrattini** [JulianFrattini/cira#61]
The following test cases do not work in my local environment:

https://github.com/JulianFrattini/cira/blob/6b53fa2f6175d4b26097350d9202a2b6e8a6898f/test/test_model_locator.py#L17-L30

They seem to work in the GitHub environment, but it would be great if they would not break locally. Where does the `mocker` parameter come from? In my environment, pytest tries to resolve it as a fixture it cannot find. Are there additional libraries necessary?

Additionally, I am not entirely sure about the implications of that test: if the `os.path.isfile` is mocked to return `False`, then I would actually expect the `__load_model_env` method in the model_locator.py file to raise a `NameError` as both conditions in which the existence of a file is checked should be evaluated to `False`.

**Comment by JulianFrattini** [comment]
This issue is currently contained in my local environment and is not urgent.

**Comment by andreas-bauer** [comment]
`mocker` is a `pytest` dependency and is part of the `setup.py` dependency declaration. Execution `pip3 install -e ".[dev]` will install `mocker` and all required development dependencies.

**Comment by JulianFrattini** [comment]
Indeed, this fixed the problem. I will add this information to the README.md file to make it clear for future users.
