### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by nirmalshah20519** [JulianFrattini/cira#82]
docker-compose up --build
Building cira
[+] Building 0.7s (12/12) FINISHED                                                                              docker:default
 => [internal] load build definition from Dockerfile                                                                      0.0s
 => => transferring dockerfile: 383B                                                                                      0.0s
 => [internal] load metadata for ghcr.io/julianfrattini/cira-dev:latest                                                   0.7s
 => [internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 2B                                                                                           0.0s
 => [1/7] FROM ghcr.io/julianfrattini/cira-dev:latest@sha256:39b66c67370c9ddafc7e3c8b89f9440f47333d08c410b38da2f1164e0c5  0.0s
 => [internal] load build context                                                                                         0.0s
 => => transferring context: 1.48kB                                                                                       0.0s
 => CACHED [2/7] WORKDIR /cira                                                                                            0.0s
 => CACHED [3/7] COPY setup.py .                                                                                          0.0s
 => CACHED [4/7] COPY README.md .                                                                                         0.0s
 => CACHED [5/7] RUN pip3 install -e .                                                                                    0.0s
 => CACHED [6/7] COPY ./src ./src                                                                                         0.0s
 => CACHED [7/7] COPY ./app.py ./app.py                                                                                   0.0s
 => exporting to image                                                                                                    0.0s
 => => exporting layers                                                                                                   0.0s
 => => writing image sha256:a9fcc6f6f24c4806ef221b563cf884297ce31a73280bf538901382d09d3de3f6                              0.0s
 => => naming to docker.io/library/cira-main_cira                                                                         0.0s
Creating ghcr.io/julianfrattini/cira:0.9.7 ... error

ERROR: for ghcr.io/julianfrattini/cira:0.9.7  Cannot create container for service cira: Invalid container name (ghcr.io/julianfrattini/cira:0.9.7), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

ERROR: for cira  Cannot create container for service cira: Invalid container name (ghcr.io/julianfrattini/cira:0.9.7), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
ERROR: Encountered errors while bringing up the project.

**Comment by andreas-bauer** [comment]
@nirmalshah20519 I guess your personal access token for ghrc.io expired.
Have a look at [Working with the Container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) and check wheter you have an active access token. 
If not, generate a new one.

**Comment by andreas-bauer** [comment]
@nirmalshah20519 Did you try it out with a new access token?

**Comment by andreas-bauer** [comment]
I'm closing this issue since it doesn't seem to be a problem with the repository.
